don't hard code ROLE

diff --git a/cmd/formation/bin/upload b/cmd/formation/bin/upload
--- a/cmd/formation/bin/upload
+++ b/cmd/formation/bin/upload
@@ -4,7 +4,7 @@ create_function() {
   aws lambda create-function \
     --function-name formation \
     --runtime nodejs \
-    --role arn:aws:iam::778743527532:role/lambda_basic_execution \
+    --role $ROLE \
     --handler lambda.external \
     --zip-file fileb://lambda.zip
 }
@@ -14,5 +14,10 @@ update_function() {
     --function-name formation \
     --zip-file fileb://lambda.zip
 }
+
+if [ "$ROLE" == "" ]; then
+  echo "ROLE required"
+  exit 1
+fi
 
 aws lambda get-function --function-name formation >/dev/null 2>&1 && update_function || create_function
